<div align="center">

<font color=0F5298 size=8>
Python 06

<font color= 6C3BAA size=6>
 <br>
Data handling
<br>
<font color=GREEN size=5>
HAKAN Fatemi (www.hooko.ir)


____

In [ ]:
f = open(r"E:\All\ipynb\hakan.txt")
print(f.read())

In [ ]:
f = open(r"E:\All\ipynb\hakan.txt", "r")

print(f.readline())
f.close()

In [ ]:
f = open(r"E:\All\ipynb\hakan.txt", "a")
f.write("\nNow the file has more content!")
f.close()

# open and read the file after the appending:
f = open(r"E:\All\ipynb\hakan.txt", "r")
print(f.read())

In [ ]:
import pandas as pd

file_path = r"E:\All\ipynb\all\salaries (2).csv"

try:
    df = pd.read_csv(file_path)
    print("csv file content:")
    print(df)
    
except FileNotFoundError:
    print("File not found! Please check the file path.")
except Exception as e:
    print(f"Error reading Excel file: {e}")

In [20]:
import pandas as pd

df = pd.read_csv(r"E:\All\ipynb\all\salaries (2).csv")

df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2024,SE,FT,AI Engineer,202730,USD,202730,US,0,US,M
1,2024,SE,FT,AI Engineer,92118,USD,92118,US,0,US,M
2,2024,SE,FT,Data Engineer,130500,USD,130500,US,0,US,M
3,2024,SE,FT,Data Engineer,96000,USD,96000,US,0,US,M
4,2024,SE,FT,Machine Learning Engineer,190000,USD,190000,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
16529,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
16530,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
16531,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
16532,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
16533,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

In [ ]:
import numpy as np
import pandas as pd

rain_golestan = float(input("Enter rainfall in Golestan (in mm): "))

print(f"Rainfall in Golestan: {rain_golestan} mm")

In [ ]:
import numpy as np

t1 = float(input("Enter number: "))
t2 = float(input("Enter number: "))

ts = t1 + t2
ta1 = ts/2
print(ta1)

ta2 = np.mean([t1, t2])
print(ta2)

12.5
12.5

In [31]:
import numpy as np
import pandas as pd

array = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", array)

data = {"City": ["Tehran", "Ahvaz", "Golestan"], "Rainfall": [200, 150, 500]}

df = pd.DataFrame(data)

df

NumPy Array: [1 2 3 4 5]

       City  Rainfall
0    Tehran       200
1     Ahvaz       150
2  Golestan       500

## Author

Mahdi Fatemi (HAKAN)

## web
www.hooko.ir

## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2025-11-06 | 1.0  | HAKAN Fatemi  |  ... |

## <h3 align="center"> © HOOKO.IR Corporation. All rights reserved. <h3/>